### ISSUE TITLE
No module named 'png.pngfilters'

### ISSUE THREAD

**Issue by cmosig** [nschloe/betterspy#17]
How would I install this? Could not find information about the submodule pngfilters.

**Comment by nschloe** [comment]
Try [this](https://github.com/nschloe/matplotx#spy-plots-betterspy).

**Comment by cmosig** [comment]
I get the exact same error.

```
ERROR:root:Error during import of compiled filters!
ERROR:root:No module named 'png.pngfilters'
ERROR:root:Fallback to pure python mode!
```

**Comment by nschloe** [comment]
Hm, no idea. Cannot reproduce.

**Comment by cmosig** [comment]
What python version are you using? I am using 3.9.

**Comment by cmosig** [comment]
Can you send the relevant packages and versions you are using? e.g `pip freeze`

**Comment by nschloe** [comment]
I'm on Python 3.10, but it should work either way, it does in the tests anyway.
```
pip freeze | grep png
```
```
pypng==0.20220715.0
```
